services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: tomcain1!
      MSSQL_AGENT_ENABLED: true
      